# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


#Word.create(:name => "", :meaning => "", :sentence =>"")

Word.create(:name => "countenance", :meaning => "the look or expression of the face, also approval or encouragement; moral support")
Word.create(:name => "facetious", :meaning => "not meant to be taken seriously or literally, lacking serious intent; amusing or frivolous")
Word.create(:name => "pedantic", :meaning => "ostentatious in one's learning, overly concerned with minute details or formalisms, especially in teaching")
Word.create(:name => "esoteric", :meaning => "understood by or meant for only the select few who have special knowledge or interest; secret or confidential")
Word.create(:name => "ambiguous", :meaning => "open to or having several possible meanings or interpretations; difficult to comprehend, distinguish, or classify")
Word.create(:name => "repudiate", :meaning => "to reject as having no authority or binding force, to cast off or disown")
Word.create(:name => "melancholy", :meaning => "affected with, characterized by, or showing sadness; mournful; soberly thoughtful")
Word.create(:name => "paradigm", :meaning => "a set of forms all of which contain a particular element, an example serving as a model or pattern")
Word.create(:name => "capricious", :meaning => "subject to, led by, or indicative of caprice or whim; erratic")
Word.create(:name => "ostentatious", :meaning => "characterized by or given to pretentious or conspicuous show in an attempt to impress others or attract notice")
Word.create(:name => "paradox", :meaning => "a statement or proposition that seems self-contradictory or absurd but in reality expresses a possible truth")
Word.create(:name => "mitigate", :meaning => "to lessen in force or intensity, as wrath, grief, harshness, or pain; moderate or make less severe")
Word.create(:name => "pragmatic", :meaning => "pertaining to a practical point of view or practical considerations")
Word.create(:name => "auspicious", :meaning => "promising success, favored by fortune; prosperous")
Word.create(:name => "plethora", :meaning => "overabundance, excess")
Word.create(:name => "lethargic", :meaning => "drowsy and sluggish")
Word.create(:name => "gullible", :meaning => "easily deceived or cheated")
Word.create(:name => "erudite", :meaning => "characterized by great knowledge; learned or scholarly")
Word.create(:name => "eclectic", :meaning => "selecting from various sources or made up of what is selected from different sources")
Word.create(:name => "obsequious", :meaning => "characterized by or showing servile complaisance or deference; fawning, servilely compliant or deferential")
Word.create(:name => "refute", :meaning => "to prove to be false or erroneous, as an opinion or charge")
Word.create(:name => "disingenuous", :meaning => "lacking in frankness, candor, or sincerity")
Word.create(:name => "lucid", :meaning => "easily understood; completely intelligible or comprehensible")
Word.create(:name => "opaque", :meaning => "not transparent or translucent; impenetrable to light; dark or dull")
Word.create(:name => "aesthetic", :meaning => "pertaining to the beautiful or the branch of philosophy dealing with such notions as the beautiful, the ugly, the sublime, the comic")
Word.create(:name => "mundane", :meaning => "pertaining to this world or earth as contrasted with heaven; earthly, common, ordinary, banal or unimaginative")
Word.create(:name => "hyperbole", :meaning => "obvious and intentional exaggeration; an extravagant statement or figure of speech not intended to be taken literally")
Word.create(:name => "loquacious", :meaning => "talking or tending to talk much, excessively or freely")
Word.create(:name => "rhetoric", :meaning => "the undue use of exaggeration or display in writing or speech; bombast")
Word.create(:name => "apathy", :meaning => "absence or suppression of passion, emotion, or excitement; lack of interest in or concern for things that others find moving or exciting")
Word.create(:name => "discretion", :meaning => "the power or right to decide or act according to one's own judgment; freedom of judgment or choice")
Word.create(:name => "articulate", :meaning => "to utter clearly and distinctly; pronounce with clarity")
Word.create(:name => "enigmatic", :meaning => "perplexing and mysterious")
Word.create(:name => "appropriate", :meaning => "to set apart and authorize for some specific purpose; to take for oneself or to take without permission or consent")
Word.create(:name => "acumen", :meaning => "keen insight or shrewdness")
Word.create(:name => "advocate", :meaning => "to speak or write in favor of; support or urge by argument; recommend publicly")
Word.create(:name => "innocuous", :meaning => "not harmful or injurious; harmless")
Word.create(:name => "gregarious", :meaning => "fond of the company of others; sociable")
Word.create(:name => "anathema", :meaning => "a person or thing detested, loathed, consigned to damnation or destruction; a formal ecclesiastical curse involving excommunication")
Word.create(:name => "banal", :meaning => "devoid of freshness or originality; hackneyed or trite")
Word.create(:name => "efficacy", :meaning => "capacity for producing a desired result or effect; effectiveness")
Word.create(:name => "benign", :meaning => "having a kindly disposition; showing or expressive of gentleness or kindness")
Word.create(:name => "meticulous", :meaning => "taking or showing extreme care about minute details; precise and thorough")
Word.create(:name => "ephemeral", :meaning => "lasting a very short time, transitory")
Word.create(:name => "succinct", :meaning => "expressed in few words; concise or terse")
Word.create(:name => "reticent", :meaning => "disposed to be silent or not to speak freely; reluctant or restrained")
Word.create(:name => "contentious", :meaning => "tending to argument or strife; causing, involving, or characterized by controversy")
Word.create(:name => "ambiguity", :meaning => "doubtfulness or uncertainty of meaning or intention")
Word.create(:name => "insipid", :meaning => "without distinctive, interesting, or stimulating qualities; vapid or bland")
Word.create(:name => "alacrity", :meaning => "cheerful readiness, promptness, or willingness")
Word.create(:name => "austere", :meaning => "severe in manner or appearance, rigorously self-disciplined and severely moral; lacking softness")
Word.create(:name => "presumptuous", :meaning => "unwarrantedly or impertinently bold; forward")
Word.create(:name => "dogmatic", :meaning => "of the nature of a dogma or doctrine, asserting opinions in an arrogant manner; opinionated")
Word.create(:name => "arcane", :meaning => "known or understood by very few; mysterious, secret or obscure")
Word.create(:name => "taciturn", :meaning => "inclined to silence; reserved in speech; dour, stern, and silent in expression and manner")
Word.create(:name => "impetuous", :meaning => "characterized by sudden or rash action; impulsive; moving with great force or violence")
Word.create(:name => "anomaly", :meaning => "a deviation from the common rule, type, arrangement, or form; an odd or peculiar condition")
Word.create(:name => "inherent", :meaning => "existing in someone or something as a permanent and inseparable element, quality, or attribute")
Word.create(:name => "pernicious", :meaning => "causing insidious harm or ruin, injury or hurt")
Word.create(:name => "spurious", :meaning => "not genuine, authentic, or true; pretended or counterfeit")
Word.create(:name => "contrite", :meaning => "showing sincere remorse; filled with a sense of guilt and the desire for atonement")
Word.create(:name => "volatile", :meaning => "tending or threatening to break out into open violence; changeable or mercurial")
Word.create(:name => "emulate", :meaning => "imitate with effort to equal or surpass or to rival with some degree of success")
Word.create(:name => "petulant", :meaning => "moved to or showing sudden, impatient irritation, especially over some trifling annoyance")
Word.create(:name => "convoluted", :meaning => "twisted or coiled; complicated or intricately involved")
Word.create(:name => "obstinate", :meaning => "firmly or stubbornly adhering to one's purpose or opinion; not yielding to argument, persuasion, or entreaty")
Word.create(:name => "laconic", :meaning => "using few words; expressing much in few words; concise")
Word.create(:name => "propensity", :meaning => "a natural inclination or tendency")
Word.create(:name => "audacious", :meaning => "extremely bold or daring; recklessly brave and fearless, also extremely original")
Word.create(:name => "pique", :meaning => "a feeling of irritation or resentment, as from a wound to pride or self-esteem")
Word.create(:name => "prosaic", :meaning => "commonplace or dull; matter-of-fact or unimaginative; having the character of prose rather than poetry")
Word.create(:name => "mercurial", :meaning => "changeable, volatile, fickle, flighty and erratic")
Word.create(:name => "hegemony", :meaning => "leadership or predominant influence exercised by one nation over others; predominance")
Word.create(:name => "exacerbate", :meaning => "to increase the severity, bitterness, or violence of; aggravate")
Word.create(:name => "nascent", :meaning => "beginning to exist or develop")
Word.create(:name => "disparate", :meaning => "distinct in kind and essentially different; dissimilar")
Word.create(:name => "avarice", :meaning => "insatiable greed for riches; miserly desire to gain and hoard wealth")
Word.create(:name => "sporadic", :meaning => "appearing or happening at irregular intervals in time; scattered or isolated instances")
Word.create(:name => "assuage", :meaning => "to make milder or less severe; relieve, ease or mitigate")
Word.create(:name => "penchant", :meaning => "a strong inclination, taste, or liking for something")
Word.create(:name => "arduous", :meaning => "requiring great exertion; laborious, using much energy and vigor; full of hardships")
Word.create(:name => "specious", :meaning => "apparently good or right though lacking real merit; superficially pleasing")
Word.create(:name => "dearth", :meaning => "an inadequate supply; scarcity; lack as during famine")
Word.create(:name => "cogent", :meaning => "convincing or believable by virtue of forcible, clear, or incisive presentation")
Word.create(:name => "ambivalence", :meaning => "uncertainty, especially when caused by inability to make a choice or by a simultaneous desire to say or do two opposite or conflicting things")
Word.create(:name => "ameliorate", :meaning => "to make or become better, more bearable, or more satisfactory; improve")
Word.create(:name => "perfunctory", :meaning => "performed merely as a routine duty; hasty and superficial; lacking interest, care, or enthusiasm; indifferent or apathetic")
Word.create(:name => "lugubrious", :meaning => "mournful, dismal, or gloomy in an affected, exaggerated, or unrelieved manner")
Word.create(:name => "pithy", :meaning => "brief, forceful, and meaningful in expression; full of vigor, substance, or meaning; terse")
Word.create(:name => "empirical", :meaning => "depending upon experience or observation alone, without using scientific method or theory")
Word.create(:name => "tenuous", :meaning => "thin or slender in form like a thread; lacking a sound basis in reasoning; an unsubstantiated or weak stand, statement or argument")
Word.create(:name => "amenable", :meaning => "ready or willing to answer, open to influence, persuasion, or advice; agreeable")
Word.create(:name => "catalyst", :meaning => "a person or thing that precipitates an event or change")
Word.create(:name => "digress", :meaning => "to deviate or wander away from the main topic or purpose in speaking or writing")
Word.create(:name => "peruse", :meaning => "to read through with thoroughness or care, to examine in detail")
Word.create(:name => "indolent", :meaning => "having or showing a disposition to avoid exertion; slothful")
Word.create(:name => "tacit", :meaning => "understood without being openly expressed; implied, unvoiced or unspoken")
Word.create(:name => "latent", :meaning => "present but not visible, apparent, or actualized; existing as potential")
Word.create(:name => "placate", :meaning => "to appease or pacify, especially by concessions or conciliatory gestures")
Word.create(:name => "eloquent", :meaning => "having or exercising the power of fluent, forceful, and appropriate speech, characterized by forceful and appropriate expression")
Word.create(:name => "ascetic", :meaning => "a person who dedicates his or her life to a pursuit of contemplative ideals and practices extreme self-denial for religious reasons")
Word.create(:name => "vindictive", :meaning => "disposed or inclined to revenge; proceeding from or showing a revengeful spirit")
Word.create(:name => "caustic", :meaning => "capable of burning, corroding, or destroying living tissue; severely critical or sarcastic")
Word.create(:name => "garrulous", :meaning => "excessively talkative in a rambling, roundabout manner, especially about trivial matters")
Word.create(:name => "recalcitrant", :meaning => "resisting authority or control, not obedient or compliant")
Word.create(:name => "precarious", :meaning => "dependent on circumstances beyond one's control; uncertain, unstable or insecure")
Word.create(:name => "anachronism", :meaning => "something or someone that is not in its correct historical or chronological time, especially one that belongs to an earlier time")
Word.create(:name => "prodigal", :meaning => "wastefully or recklessly extravagant or lavish")
Word.create(:name => "diatribe", :meaning => "a bitter, sharply abusive denunciation, attack, or criticism")
Word.create(:name => "bane", :meaning => "a person or thing that ruins or spoils")
Word.create(:name => "morose", :meaning => "gloomily or sullenly ill-humored, as a person or mood; characterized by or expressing gloom")
Word.create(:name => "verbose", :meaning => "characterized by the use of many or too many words")
Word.create(:name => "deleterious", :meaning => "injurious to health")
Word.create(:name => "onerous", :meaning => "burdensome, oppressive, or troublesome; having obligations or that outweigh the advantages")
Word.create(:name => "rescind", :meaning => "to annul, revoke or repeal, to invalidate by a later action or a higher authority")
Word.create(:name => "axiom", :meaning => "a self-evident truth that requires no proof, a universally accepted principle or rule")
Word.create(:name => "abate", :meaning => "to reduce in amount, degree, or intensity")
Word.create(:name => "assiduous", :meaning => "unremitting; constant in application or effort; working diligently at a task")
Word.create(:name => "admonish", :meaning => "to caution, advise, to reprove or scold in a mild and good-willed manner")
Word.create(:name => "ostensible", :meaning => "outwardly appearing, professed or pretended")
Word.create(:name => "corroborate", :meaning => "to make more certain; confirm")
Word.create(:name => "lament", :meaning => "to feel or express sorrow or regret for, to mourn for something or someone")
Word.create(:name => "sagacious", :meaning => "having or showing acute mental discernment and keen practical sense; shrewd")
Word.create(:name => "sanction", :meaning => "authoritative permission that serves to support an action or condition")
Word.create(:name => "paucity", :meaning => "smallness of quantity, scarcity, insufficiency of number")
Word.create(:name => "fervent", :meaning => "having or showing great warmth or intensity of spirit, feeling, enthusiasm; ardent")
Word.create(:name => "terse", :meaning => "neatly or effectively concise, brief and pithy")
Word.create(:name => "bombastic", :meaning => "high-sounding, inflated or pretentious speech or writing")
Word.create(:name => "malevolent", :meaning => "wishing evil or harm to another or others; showing ill will")
Word.create(:name => "whimsical", :meaning => "given to whimsy or fanciful notions; capricious")
Word.create(:name => "decorum", :meaning => "dignified propriety of behavior, speech and dress; an observance or requirement of polite society")
Word.create(:name => "abscond", :meaning => "to depart in a sudden and secret manner, especially to avoid capture and legal prosecution")
Word.create(:name => "connoisseur", :meaning => "a person who is especially competent to pass critical judgments in an art, particularly one of the fine arts, or in matters of taste")
Word.create(:name => "obdurate", :meaning => "unmoved by persuasion, pity, or tender feelings; stubborn, unyielding")
Word.create(:name => "resolute", :meaning => "firmly resolved or determined, characterized by firmness and determination")
Word.create(:name => "apocryphal", :meaning => "of doubtful authorship or authenticity")
Word.create(:name => "diffident", :meaning => "lacking confidence in one's own ability, worth, or fitness; restrained or reserved in manner or conduct")
Word.create(:name => "zealot", :meaning => "an excessively zealous person or a fanatic")
Word.create(:name => "archaic", :meaning => "marked by the characteristics of an earlier period; antiquated or primitive")
Word.create(:name => "guile", :meaning => "insidious cunning in attaining a goal; crafty or artful deception")
Word.create(:name => "inchoate", :meaning => "not yet completed or fully developed; just begun; incipient; not organized")
Word.create(:name => "ingenuous", :meaning => "free from reserve, restraint, or dissimulation; candid or sincere")
Word.create(:name => "fortuitous", :meaning => "happening or produced by chance; lucky or fortunate")
Word.create(:name => "endemic", :meaning => "characteristic of a specific people or place; native or indigenous")
Word.create(:name => "fatuous", :meaning => "foolish or inane, especially in an unconscious, complacent manner; silly")
Word.create(:name => "halcyon", :meaning => "calm and tranquil; rich and prosperous; happy and carefree")
Word.create(:name => "disparage", :meaning => "to treat slightingly or belittle")
Word.create(:name => "irascible", :meaning => "easily provoked to anger; very irritable")
Word.create(:name => "propriety", :meaning => "conformity to established standards of good or proper behavior or manners")
Word.create(:name => "misanthrope", :meaning => "a person who dislikes other people")
Word.create(:name => "hackneyed", :meaning => "made commonplace or trite; stale or banal")
Word.create(:name => "vindicate", :meaning => "to clear, as from an accusation, imputation or suspicion; to uphold or justify by argument or evidence")
Word.create(:name => "acerbic", :meaning => "sour or astringent in taste; harsh or severe, as of temper or expression")
Word.create(:name => "approbation", :meaning => "approval; commendation or official sanction")
Word.create(:name => "platitude", :meaning => "a flat, dull, or trite remark uttered as if it were fresh or profound")
Word.create(:name => "sordid", :meaning => "morally ignoble or base; meanly selfish, self-seeking, or mercenary")
Word.create(:name => "impede", :meaning => "to retard in movement or progress by means of obstacles or hindrances")
Word.create(:name => "precipitate", :meaning => "to hasten the occurrence of; bring about prematurely, or to cast or plunge violently")
Word.create(:name => "maverick", :meaning => "an unbranded calf that is separated from its mother, or a lone dissenter who takes an independent stand apart from his or her associates")
Word.create(:name => "perennial", :meaning => "lasting for an indefinitely long time; enduring")
Word.create(:name => "adroit", :meaning => "expert or nimble in the use of the hands or body; cleverly skillful, resourceful, or ingenious")
Word.create(:name => "quotidian", :meaning => "daily, usual or customary; everyday")
Word.create(:name => "flippant", :meaning => "frivolously disrespectful, shallow, or lacking in seriousness; characterized by levity")
Word.create(:name => "pusillanimous", :meaning => "lacking courage or resolution; timid")
Word.create(:name => "levity", :meaning => "lightness of mind, character, or behavior; lack of appropriate seriousness or earnestness")
Word.create(:name => "tirade", :meaning => "a prolonged outburst of bitter, outspoken denunciation")
Word.create(:name => "obviate", :meaning => "to anticipate and prevent or eliminate difficulties by effective measures; render unnecessary")
Word.create(:name => "inscrutable", :meaning => "incapable of being investigated, analyzed, or scrutinized; not easily understood; mysterious")
Word.create(:name => "odious", :meaning => "deserving or causing hatred; highly offensive")
Word.create(:name => "blithe", :meaning => "joyous, merry, or gay in disposition; without thought or regard")
Word.create(:name => "phlegmatic", :meaning => "not easily excited to action or display of emotion; self-possessed, calm, or composed")
Word.create(:name => "deference", :meaning => "respectful submission or yielding to the judgment, opinion or will of another")
Word.create(:name => "paragon", :meaning => "a model or pattern of excellence or of a particular excellence")
Word.create(:name => "voracious", :meaning => "craving or consuming large quantities of food; exceedingly eager or avid")
Word.create(:name => "soporific", :meaning => "causing sleep; characterized by drowsiness")
Word.create(:name => "accolade", :meaning => "award, honor, or laudatory notice; originally a light touch on the shoulder with the flat side of the sword in the ceremony of conferring knighthood")
Word.create(:name => "feign", :meaning => "to invent fictitiously or deceptively, as a story or an excuse")
Word.create(:name => "extant", :meaning => "still existing, not destroyed or lost")
Word.create(:name => "abeyance", :meaning => "temporary inactivity, cessation, or suspension")
Word.create(:name => "prevaricate", :meaning => "to speak falsely, deliberately misstate or create an incorrect impression; to lie")
Word.create(:name => "antipathy", :meaning => "a basic, or habitual repugnance; aversion or dislike")
Word.create(:name => "boisterous", :meaning => "rough and noisy, jolly or rowdy; clamorous and unrestrained")
Word.create(:name => "propitious", :meaning => "presenting favorable conditions; auspicious")
Word.create(:name => "salacious", :meaning => "lustful or lecherous; obscene writing or photographs")
Word.create(:name => "appease", :meaning => "to bring to a state of peace, quiet, ease, calm, or contentment")
Word.create(:name => "dilettante", :meaning => "a person who takes up an art, activity, or subject merely for amusement, especially in a superficial way; a dabbler")
Word.create(:name => "aberrant", :meaning => "departing from the right, normal, or usual course; exceptional")
Word.create(:name => "umbrage", :meaning => "offense, annoyance or displeasure; the slightest indication or vaguest feeling of suspicion, doubt or hostility")
Word.create(:name => "invidious", :meaning => "calculated to create ill will, resentment or give offense; hateful")
Word.create(:name => "filial", :meaning => "pertaining to or befitting a son or daughter; noting or having the relation of a child to a parent")
Word.create(:name => "elegy", :meaning => "a mournful, melancholy poem, especially in remembrance of the dead")
Word.create(:name => "truculent", :meaning => "fierce; cruel; brutally harsh or aggressively hostile")
Word.create(:name => "iconoclast", :meaning => "a person who attacks cherished beliefs, traditional institutions, or religions as being based on error or superstition")
Word.create(:name => "incipient", :meaning => "beginning to exist or appear; in an initial stage")
Word.create(:name => "anomalous", :meaning => "deviating from or inconsistent with the common order, form, or rule; not fitting into a common or type or pattern")
Word.create(:name => "partisan", :meaning => "an adherent or supporter of a person, group, party, or cause, especially one that shows a biased, emotional allegiance")
Word.create(:name => "opprobrium", :meaning => "the disgrace incurred by conduct considered outrageously shameful; infamy")
Word.create(:name => "exigent", :meaning => "requiring immediate action or aid; requiring a great deal, or more than is reasonable")
Word.create(:name => "vacillate", :meaning => "to waver in mind or opinion; be indecisive or irresolute")
Word.create(:name => "desultory", :meaning => "lacking in consistency or visible order; random")
Word.create(:name => "lassitude", :meaning => "weariness of body or mind from strain; a condition of indolent indifference")
Word.create(:name => "apposite", :meaning => "suitable, well-adapted, pertinent, relevant or apt")
Word.create(:name => "inhibit", :meaning => "to restrain, hinder, arrest, or check; to prohibit or forbid")
Word.create(:name => "implacable", :meaning => "not to be appeased, mollified, or pacified")
Word.create(:name => "eulogy", :meaning => "a speech or writing in praise and in honor of a deceased person")
Word.create(:name => "effrontery", :meaning => "shameless or impudent boldness; barefaced audacity")
Word.create(:name => "inimical", :meaning => "adverse in tendency or effect, unfavorable; unfriendly or hostile")
Word.create(:name => "turgid", :meaning => "swollen, distended, tumid; overblown or pompous")
Word.create(:name => "bolster", :meaning => "to support with a pillow or cushion, or to support and uphold")
Word.create(:name => "pristine", :meaning => "having its original purity; uncorrupted or unsullied")
Word.create(:name => "neophyte", :meaning => "a beginner or novice, a person newly converted to a belief, as a heathen, heretic, or nonbeliever")
Word.create(:name => "credulous", :meaning => "willing to believe or trust too readily without proper or adequate evidence; gullible")
Word.create(:name => "anodyne", :meaning => "a medicine that relieves or allays pain")
Word.create(:name => "iniquity", :meaning => "gross injustice or wickedness; a violation of right or duty")
Word.create(:name => "apotheosis", :meaning => "the elevation or exaltation of a person to the rank of a god; an ideal example")
Word.create(:name => "exonerate", :meaning => "to clear, as of an accusation; free from guilt or blame")
Word.create(:name => "demur", :meaning => "the act of making objection")
Word.create(:name => "dissonance", :meaning => "inharmonious or harsh sound; a simultaneous combination of tones conventionally accepted as being in a state of needing completion")
Word.create(:name => "viscous", :meaning => "of a thick nature or consistency")
Word.create(:name => "rue", :meaning => "to feel sorrow over or regret bitterly; to wish that something had never taken place")
Word.create(:name => "salubrious", :meaning => "favorable to or promoting health")
Word.create(:name => "pungent", :meaning => "sharply affecting the organs of taste or smell, as if by a penetrating power; biting or acrid")
Word.create(:name => "flout", :meaning => "to treat with disdain, scorn, or contempt")
Word.create(:name => "reprobate", :meaning => "morally depraved, unprincipled or bad; rejected by God and beyond hope of salvation")
Word.create(:name => "inert", :meaning => "having no inherent power of action, motion, or resistance")
Word.create(:name => "abstain", :meaning => "to hold oneself back voluntarily, especially from something regarded as improper or unhealthy")
Word.create(:name => "apprise", :meaning => "to give notice to; inform or advise")
Word.create(:name => "amalgamate", :meaning => "to combine, unite, merge, or coalesce")
Word.create(:name => "castigate", :meaning => "to criticize or reprimand severely, or punish in order to correct")
Word.create(:name => "apostate", :meaning => "a person who forsakes his religion, cause or party")
Word.create(:name => "luminous", :meaning => "radiating or reflecting light; shining; bright; enlightened, as in a writer or a writer's works")
Word.create(:name => "engender", :meaning => "to produce, cause, or give rise to")
Word.create(:name => "belie", :meaning => "show to be false; to misrepresent or act unworthily according to some standard")
Word.create(:name => "chicanery", :meaning => "trickery or deception by quibbling or sophistry")
Word.create(:name => "derivative", :meaning => "not original but secondary")
Word.create(:name => "fallacious", :meaning => "containing a fallacy; logically unsound or misleading")
Word.create(:name => "noxious", :meaning => "harmful or injurious to health or physical well-being; morally harmful, corrupting or pernicious")
Word.create(:name => "august", :meaning => "inspiring reverence or admiration; of supreme dignity or grandeur; majestic")
Word.create(:name => "immutable", :meaning => "unchangeable, changeless")
Word.create(:name => "enervate", :meaning => "to deprive of force or strength; destroy the vigor of and weaken")
Word.create(:name => "exhort", :meaning => "to urge, advise, or caution earnestly; urgently admonish")
Word.create(:name => "itinerant", :meaning => "traveling from place to place, journeying")
Word.create(:name => "harangue", :meaning => "a scolding or a long or intense verbal attack; a long, passionate, vehement speech delivered before a public gathering")
Word.create(:name => "venerate", :meaning => "to regard or treat with reverence")
Word.create(:name => "stint", :meaning => "to limit to a certain amount, number, share, or allowance, often inappropriately")
Word.create(:name => "recondite", :meaning => "dealing with very profound or difficult subject matter; beyond ordinary knowledge or understanding")
Word.create(:name => "precursor", :meaning => "a person, animal, or thing that goes before and indicates the approach of someone or something else; harbinger")
Word.create(:name => "perfidy", :meaning => "deliberate breach of faith or trust")
Word.create(:name => "imperious", :meaning => "domineering in a haughty manner; dictatorial or overbearing")
Word.create(:name => "renege", :meaning => "to break a rule of play or go back on one's word")
Word.create(:name => "attenuate", :meaning => "to weaken or reduce in force, intensity, effect, quantity, or value; to make thin, slender or fine")
Word.create(:name => "stolid", :meaning => "not easily stirred or moved mentally; unemotional or impassive")
Word.create(:name => "probity", :meaning => "integrity and uprightness; honesty")
Word.create(:name => "gauche", :meaning => "lacking social grace, sensitivity, or acuteness; awkward, crude or tactless")
Word.create(:name => "culpable", :meaning => "deserving blame or censure; blameworthy")
Word.create(:name => "intractable", :meaning => "not easily controlled or directed; not docile or manageable; stubborn")
Word.create(:name => "subpoena", :meaning => "the usual writ for the summoning of witnesses or the submission of evidence, as records or documents, before a court")
Word.create(:name => "impugn", :meaning => "to challenge as false; to cast doubt upon")
Word.create(:name => "tortuous", :meaning => "full of twists, turns, or bends; not direct or straightforward, as in procedure or speech")
Word.create(:name => "laud", :meaning => "to praise, extol")
Word.create(:name => "insular", :meaning => "of or pertaining to an island or islands, or detached and isolated")
Word.create(:name => "churlish", :meaning => "boorish and rude, difficult to work or deal with")
Word.create(:name => "reverent", :meaning => "feeling, exhibiting, or characterized by reverence; deeply respectful")
Word.create(:name => "noisome", :meaning => "offensive or disgusting, such as an odor; harmful or injurious to health")
Word.create(:name => "equivocate", :meaning => "to use ambiguous or unclear expressions, usually to avoid commitment or in order to mislead")
Word.create(:name => "pedestrian", :meaning => "lacking in vitality, imagination or distinction; commonplace or dull")
Word.create(:name => "fell", :meaning => "an upland pasture, moor, or thicket; a highland plateau")
Word.create(:name => "compendium", :meaning => "a brief account of an extensive subject; a summary")
Word.create(:name => "impecunious", :meaning => "having little or no money; penniless, poor")
Word.create(:name => "excoriate", :meaning => "to denounce or berate severely; to strip off or remove the skin from; verbally flay")
Word.create(:name => "homogeneous", :meaning => "composed of parts or elements that are all of the same kind; of the same kind or nature")
Word.create(:name => "officious", :meaning => "objectionably aggressive in offering one's unrequested and unwanted services, help, or advice; meddlesome")
Word.create(:name => "confound", :meaning => "to perplex or amaze by a sudden disturbance or surprise; to throw into confusion or disorder")
Word.create(:name => "dissolution", :meaning => "the act or process of resolving or dissolving into parts or elements, the undoing or breaking of a bond, tie, union or partnership")
Word.create(:name => "sedulous", :meaning => "diligent in application or attention; persistently or carefully maintained")
Word.create(:name => "inundate", :meaning => "to flood or cover with water; deluge, or to overwhelm")
Word.create(:name => "trenchant", :meaning => "incisive or keen, as language or a person; vigorous, effective and energetic")
Word.create(:name => "intransigent", :meaning => "refusing to agree or compromise; inflexible")
Word.create(:name => "occlude", :meaning => "to close, shut, or stop up")
Word.create(:name => "pervade", :meaning => "to become spread throughout all parts of")
Word.create(:name => "fledgling", :meaning => "young, new, or inexperienced")
Word.create(:name => "palliate", :meaning => "to relieve or lessen without curing; to try to conceal the gravity of an offense by excuses or apologies")
Word.create(:name => "denigrate", :meaning => "to speak damagingly in a derogatory manner; to treat or represent as lacking in value or importance")
Word.create(:name => "philanthropic", :meaning => "pertaining to or engaged in benevolent giving, engaging in the betterment of condition for others; charitable work")
Word.create(:name => "augury", :meaning => "the art or practice of divination or a related omen, token, or indication")
Word.create(:name => "solicitous", :meaning => "anxious or concerned about; desirous or eager")
Word.create(:name => "deprecate", :meaning => "to express earnest disapproval of; to protest against a scheme")
Word.create(:name => "mendacious", :meaning => "telling lies, habitually dishonest, untruthful")
Word.create(:name => "relegate", :meaning => "to send or consign to an inferior position, place, or condition")
Word.create(:name => "mollify", :meaning => "to soften in feeling or temper; pacify or appease; reduce or soften")
Word.create(:name => "perfidious", :meaning => "deliberately faithless, treacherous or deceitful")
Word.create(:name => "foment", :meaning => "to instigate or foster discord or ill feeling")
Word.create(:name => "torpid", :meaning => "inactive or sluggish; slow; dull or lethargic")
Word.create(:name => "turpitude", :meaning => "vile, shameful or base character or act")
Word.create(:name => "deride", :meaning => "to laugh at in scorn or contempt; scoff, jeer or mock")
Word.create(:name => "satiate", :meaning => "to supply with anything to excess, so as to disgust or weary; or to satisfy to the full")
Word.create(:name => "proscribe", :meaning => "to denounce or condemn as dangerous or harmful; prohibit or banish into exile")
Word.create(:name => "vitiate", :meaning => "to impair or weaken the effectiveness of; invalidate")
Word.create(:name => "fawn", :meaning => "to seek notice or favor by servile demeanor or to behave affectionately")
Word.create(:name => "mendacity", :meaning => "the quality of being untruthful, an instance of lying")
Word.create(:name => "magnanimity", :meaning => "the quality of being extremely generous")
Word.create(:name => "din", :meaning => "a loud, confused noise, continued or tumultuous")
Word.create(:name => "dilatory", :meaning => "tending to delay or procrastinate; to slow")
Word.create(:name => "prolix", :meaning => "extended to great, unnecessary, or tedious length; long and wordy")
Word.create(:name => "venal", :meaning => "willing to sell one's influence in return for a bribe")
Word.create(:name => "penury", :meaning => "extreme poverty or destitution")
Word.create(:name => "dissemble", :meaning => "to give a false or misleading appearance to; conceal the truth or real nature of something in a feign")
Word.create(:name => "propitiate", :meaning => "to make favorably inclined; appease")
Word.create(:name => "aver", :meaning => "to assert with confidence; declare in a positive or peremptory manner")
Word.create(:name => "timorous", :meaning => "full of fear, subject to fear; timid")
Word.create(:name => "peremptory", :meaning => "leaving no opportunity for denial or refusal; imperative, decisive or final")
Word.create(:name => "felicitous", :meaning => "well-suited for the occasion, as an action, manner, or expression; apt or appropriate")
Word.create(:name => "salutary", :meaning => "promoting or conducive to health; wholesome")
Word.create(:name => "temperate", :meaning => "moderate or self-restrained; not extreme in opinion, statement, or overly indulgent in appetite or passion")
Word.create(:name => "florid", :meaning => "reddish, ruddy or rosy; flowery or excessively ornate")
Word.create(:name => "fetid", :meaning => "having an offensive odor; stinking")
Word.create(:name => "craven", :meaning => "cowardly, contemptibly timid, pusillanimous")
Word.create(:name => "dirge", :meaning => "a funeral song expressing mourning in commemoration of the dead")
Word.create(:name => "complaisant", :meaning => "inclined or disposed to please; agreeable or gracious")
Word.create(:name => "munificent", :meaning => "extremely liberal in giving; very generous")
Word.create(:name => "recant", :meaning => "to withdraw or disavow a statement or opinion; to formally retract")
Word.create(:name => "aspersion", :meaning => "a damaging or derogatory remark or criticism; the act of slandering")
Word.create(:name => "saturnine", :meaning => "sluggish in temperament; gloomy or taciturn")
Word.create(:name => "tractable", :meaning => "easily managed or controlled; docile; easily worked, shaped, or otherwise handled")
Word.create(:name => "accretion", :meaning => "an increase by natural growth or by gradual external addition; growth in size or extent")
Word.create(:name => "impassive", :meaning => "without emotion, unmoved; calm or serene")
Word.create(:name => "strut", :meaning => "to walk with a vain, pompous bearing, as with head erect and chest thrown out")
Word.create(:name => "ebullience", :meaning => "high spirits, exhilaration or exuberance")
Word.create(:name => "talisman", :meaning => "a stone, ring, or other object supposed to possess occult powers to be worn as an amulet or charm")
Word.create(:name => "burgeon", :meaning => "to grow or develop quickly; flourish")
Word.create(:name => "gossamer", :meaning => "a fine, filmy cobweb seen on grass or bushes or floating in the air in calm weather; any thin, light fabric with this quality")
Word.create(:name => "fervid", :meaning => "heated or vehement in spirit, enthusiasm; burning, glowing or intensely hot")
Word.create(:name => "refractory", :meaning => "hard or impossible to manage; stubbornly disobedient")
Word.create(:name => "tendentious", :meaning => "having or showing a definite tendency, bias, or purpose")
Word.create(:name => "dupe", :meaning => "a person who is easily deceived, a gullible person who unquestioningly or unwittingly serves a cause or another person")
Word.create(:name => "astringent", :meaning => "harshly biting, stern or severe; sharply incisive or pungent")
Word.create(:name => "oscillate", :meaning => "to swing or move to and fro, as a pendulum does, or to vacillate between differing beliefs, opinions or conditions")
Word.create(:name => "turbid", :meaning => "not clear or transparent because of stirred-up sediment; clouded, opaque or obscured")
Word.create(:name => "waver", :meaning => "an act of fluttering or vacillating")
Word.create(:name => "discordant", :meaning => "being at variance; disagreeing or harsh")
Word.create(:name => "panegyric", :meaning => "a lofty oration or writing in praise of a person or thing; an eulogy")
Word.create(:name => "expiate", :meaning => "make amends or reparation for")
Word.create(:name => "encomium", :meaning => "a formal expression of high praise; eulogy")
Word.create(:name => "aggrandize", :meaning => "to widen in scope, enlarge or extend, to make greater in power, wealth, rank, or honor")
Word.create(:name => "buttress", :meaning => "any prop or support built to steady a structure by opposing its outward thrusts")
Word.create(:name => "adumbrate", :meaning => "to produce a faint image or resemblance of; to foreshadow, darken or partially conceal")
Word.create(:name => "untoward", :meaning => "unfavorable or unfortunate; improper")
Word.create(:name => "antagonism", :meaning => "an active hostility or opposition, as between unfriendly or conflicting groups; an opposing force or tendency")
Word.create(:name => "multifaceted", :meaning => "having many facets, such as a gem, or having many aspects or phases")
Word.create(:name => "exculpate", :meaning => "to clear from a charge of guilt or fault; free from blame")
Word.create(:name => "flag", :meaning => "to fall off in vigor, energy, activity, interest; to hang loosely or droop")
Word.create(:name => "veracious", :meaning => "habitually speaking the truth; characterized by truthfulness; honest in content")
Word.create(:name => "sinuous", :meaning => "having many curves, bends, or turns; winding and indirect; devious.")
Word.create(:name => "imperturbable", :meaning => "incapable of being upset or agitated; not easily excited, calm")
Word.create(:name => "penurious", :meaning => "extremely stingy, parsimonious or miserly; extremely poor")
Word.create(:name => "daunt", :meaning => "to overcome with fear; intimidate")
Word.create(:name => "adulterate", :meaning => "to debase or make impure by adding inferior materials or elements")
Word.create(:name => "desiccate", :meaning => "to become thoroughly dried or dried up")
Word.create(:name => "libertine", :meaning => "a person who is morally or sexually unrestrained, or a freethinker in religious matters")
Word.create(:name => "limpid", :meaning => "clear and transparent, such as water, crystal, or air; completely calm, without distress or worry")
Word.create(:name => "baleful", :meaning => "full of menacing or malign influences")
Word.create(:name => "asperity", :meaning => "harshness or sharpness of tone or manner; roughness and unevenness")
Word.create(:name => "rent", :meaning => "an opening made by rending or tearing; a breach of relations or union between individuals or groups")
Word.create(:name => "reproof", :meaning => "the act of reproving, censuring, or rebuking")
Word.create(:name => "remonstrate", :meaning => "to say or plead in protest, objection, or disapproval")
Word.create(:name => "disinterested", :meaning => "unbiased by personal interest or advantage; not influenced by selfish motives")
Word.create(:name => "guileless", :meaning => "free from guile; sincere, honest, straightforward, frank")
Word.create(:name => "emollient", :meaning => "having the power of softening or relaxing, such as for the skin")
Word.create(:name => "gainsay", :meaning => "to deny, dispute, or contradict; to speak or act against; oppose")
Word.create(:name => "mordant", :meaning => "sharply caustic or sarcastic, as wit or a speaker; burning or corrosive")
Word.create(:name => "fetter", :meaning => "a chain or shackle placed on the feet; anything that confines or restrains")
Word.create(:name => "qualify", :meaning => "to modify or limit in some way; make less strong or positive")
Word.create(:name => "disabuse", :meaning => "to free a person from deception or error")
Word.create(:name => "auspice", :meaning => "patronage; support; sponsorship ; a divination or prognostication, originally from observing birds")
Word.create(:name => "alloy", :meaning => "composed of two or more metals, often a less costly metal mixed with a more valuable one")
Word.create(:name => "undulate", :meaning => "to move with a wavelike motion; display a smooth rising-and-falling or side-to-side alternation of movement")
Word.create(:name => "coda", :meaning => "in music, an independent passage at the end of a composition, made to bring it to a satisfactory close; anything that serves as a conclusion")
Word.create(:name => "tyro", :meaning => "a beginner in learning anything")
Word.create(:name => "cacophonous", :meaning => "having a harsh or discordant sound")
Word.create(:name => "bent", :meaning => "direction taken, as by one's interests; a capacity of endurance")
Word.create(:name => "inveigh", :meaning => "to protest strongly or attack vehemently with words")
Word.create(:name => "forestall", :meaning => "to prevent by action in advance, anticipate, or to buy up goods in advance in order to increase the price when resold")
Word.create(:name => "peccadillo", :meaning => "a very minor offense, a trifling fault")
Word.create(:name => "fulminate", :meaning => "to explode with a loud noise, or to issue denunciations against")
Word.create(:name => "malinger", :meaning => "to pretend illness, especially in order to shirk one's duty or avoid work")
Word.create(:name => "burnish", :meaning => "to polish a surface by friction to make smooth and bright")
Word.create(:name => "vituperate", :meaning => "to use or address with harsh or abusive language; revile")
Word.create(:name => "arrant", :meaning => "downright, thorough, unmitigated, notorious")
Word.create(:name => "slake", :meaning => "to allay by satisfying; to make less active, vigorous, intense")
Word.create(:name => "descry", :meaning => "to see something unclear or distant by looking carefully; to discover or detect")
Word.create(:name => "rancorous", :meaning => "full of resentment or spite")
Word.create(:name => "pillory", :meaning => "to expose to public derision, ridicule, or abuse")
Word.create(:name => "beneficent", :meaning => "doing good, conferring benefits; kind in action or purpose")
Word.create(:name => "plastic", :meaning => "capable of being molded or of receiving form; pliable and impressionable")
Word.create(:name => "martinet", :meaning => "a strict disciplinarian, especially a military one; someone who stubbornly adheres to methods or rules")
Word.create(:name => "arrest", :meaning => "to catch and hold, attract and fix, to stop and slow down")
Word.create(:name => "headlong", :meaning => "undertaken quickly and suddenly; hasty")
Word.create(:name => "indigence", :meaning => "seriously impoverished condition; poverty")
Word.create(:name => "arabesque", :meaning => "a sinuous, spiraling, undulating, or serpentine line or linear motif, often used in the Fine Arts")
Word.create(:name => "abnegate", :meaning => "to refuse or deny oneself some rights or conveniences; to reject or renounce")
Word.create(:name => "shard", :meaning => "a fragment such as broken earthenware, glass or shell")
Word.create(:name => "minatory", :meaning => "menacing, threatening")
Word.create(:name => "welter", :meaning => "to roll, toss, or heave, as waves or the sea; to roll, writhe or tumble about")
Word.create(:name => "striated", :meaning => "marked with narrow furrows or ridges; striped or streaked")
Word.create(:name => "simper", :meaning => "a silly, self-conscious smile")
Word.create(:name => "cadge", :meaning => "to obtain by imposing on another's generosity or friendship, to borrow without intent to repay")
Word.create(:name => "depredation", :meaning => "the act of preying upon or plundering")
Word.create(:name => "rarefy", :meaning => "to make more refined, spiritual, or exalted")
Word.create(:name => "raillery", :meaning => "good-humored ridicule or banter")
Word.create(:name => "artless", :meaning => "free from deceit or cunning; natural, simple, uncontrived")
Word.create(:name => "idolatrous", :meaning => "worshiping idols or blindly adoring")
Word.create(:name => "insensible", :meaning => "incapable of feeling or perceiving; deprived of sensation; unconscious")
Word.create(:name => "bedizen", :meaning => "to dress or adorn in a showy, gaudy, or tasteless manner")
Word.create(:name => "novitiate", :meaning => "the state or period of being a novice of a religious order or congregation; the state or period of being a beginner in anything")
Word.create(:name => "grandiloquence", :meaning => "speech that is lofty in tone, often to the point of being pompous or bombastic")
Word.create(:name => "blandish", :meaning => "to coax or influence by gentle flattery; cajole")
Word.create(:name => "beatify", :meaning => "to make blissfully happy; in the Roman Catholic Church, to declare to be among the blessed entitled to specific religious honor")
Word.create(:name => "Stoic", :meaning => "pertaining to the philosophy that people should be free from passion, unmoved by joy or grief, and submit without complaint to unavoidable necessity")
Word.create(:name => "credulity", :meaning => "readiness to believe on the basis of weak evidence", :sentence =>"Con artists take advantage of people's credulity")
Word.create(:name => "querulous", :meaning => "fussy and full of complaints", :sentence =>"toddles are querulous if they miss their nap")
Word.create(:name => "clemency", :meaning => "disposition to be lenient", :sentence =>"some judges are known for their clemency towards first time offenders")
